name: Using concurrency to cancel any in-progress job or run

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} - ${{ github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # This job will run for 5 minutes
      - run: sleep 300
