name: Test out my composite action in a workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: "Who to greet"
        default: "World"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: gamertense/hello-world-composite-action@v1
        with:
          who-to-greet: ${{ github.event.inputs.who-to-greet }}
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
