name: "Prevent a job from failure"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  continue-on-error:
    runs-on: ubuntu-latest
    steps:
      - name: "Run a command that fails"
        run: exit 1
        continue-on-error: true
