name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Building the app"
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com
    steps:
      - name: deploy
        # Put API_KEY in api_key.txt file and print file content in the logs.
        run: |
          echo "Deploying the app"
          echo "API_KEY from secrets: $API_KEY" >> api_key.txt
          echo "API_KEY from expression: ${{ secrets.api_key }}" >> api_key_expression.txt
          cat api_key.txt
          cat api_key_expression.txt
          echo "::debug::DOMAIN_NAME: $DOMAIN_NAME"
        env:
          API_KEY: ${{ secrets.api_key }}
          DOMAIN_NAME: ${{ vars.domain_name }}
