name: Example workflow using GITHUB_ACTION_REPOSITORY
on: [push]

jobs:
  print-action-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GITHUB_ACTION_REPOSITORY
        run: echo "The action repository is $GITHUB_ACTION_REPOSITORY"
        env:
          GITHUB_ACTION_REPOSITORY: ${{ github.action_repository }}
