name: Receive webhook event

on:
  repository_dispatch:
    types: [webhook]

jobs:
  respond-to-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Print event name
        run: echo "Event name is ${{ github.event_name }}"
      - name: Print the event payload
        run: echo "${{ github.event.client_payload }}"
